//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSmartphones.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_2119110227
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> UpdateOnUtc { get; set; }
    }
}
